### ISSUE TITLE
Add German Scratch Cards

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-resources#10]
Animate Your Name and Dance coding cards in German:
https://drive.google.com/drive/folders/0B2D5LbbBeLfUdW8wcGprNVMtZGs

**Comment by chrisgarrity** [comment]
@seotts this will be a good time to show you the new resources workflow.

**Comment by tiemes** [comment]
We are currently working on Catchgame and Story Cards.

**Comment by chrisgarrity** [comment]
@tiemes excellent, we look forward to your pull request or email. Also, since this is a new process, please let us know if you have feedback on ways to make it better for translators.
