### ISSUE TITLE
printer-unfriendly and timeconsuming card layout

### ISSUE THREAD

**Issue by tiemes** [LLK/scratch-resources#13]
Having people print out, cut out and glue the cards together is extremely time consuming. We therefore created our German translation of catchgame cards without the cut/glue border. We use a layout where four cards fit onto one A4 page with an border of 5mm on each side after cutting them in four pieces. We only need two cuts on a cutting machine and even have them in the right order this way. (Order works only for one set at a time, needs some sorting if more than one.)
I would suggest to change the layout to something more userfriendly.

**Comment by chrisgarrity** [comment]
@tiemes thanks for the feedback, the cards are going to be revised for Scratch 3.0
