### ISSUE TITLE
Add Brazilian Portuguese resources

### ISSUE THREAD

**Issue by seotts** [LLK/scratch-resources#16]
Getting Started: https://resources.scratch.mit.edu/www/guides/pt-br/Getting-Started-Guide-Scratch2.pdf

Note from Leo about Getting Started:

> Even though the translation already exists and seems to be available in the code base (check the  pdfs->help->pt-br folder), the link from https://scratch.mit.edu/tips seems to be pointing to the English version of the file. From what I noticed, the same problem seems to happen for other languages such as French, too.

Scratch Cards (one PDF): https://www.dropbox.com/s/gwabo4taxvsy547/ScratchCardsAll.pdf?dl=0
Scratch Cards (separated): https://www.dropbox.com/sh/td6fea1xojynyz5/AAAnfsMpuh5BJfzgWI5pBJCma?dl=0

Educator guides: https://www.dropbox.com/sh/b0g21tgaf87qcir/AADpD1nn5awB10o0QPJtD5dia?dl=0

**Comment by seotts** [comment]
@chrisgarrity Is the issue Leo brought up about Getting Started going to be fixed after the deploy?

**Comment by chrisgarrity** [comment]
Yes, this should be resolved after the deploy
