### ISSUE TITLE
Educator Guide problems:

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-resources#34]
There are a few problems in the inDesign sources we provide to translators (perhaps the pptx as well). None of these problems appear in the PDF versions, so it may just be a case of updating the source files to the latest versions.

### Pet Guide
- setting up Scratch Accounts - `Participants can sign up for their own Scratch accounts at` is missing replaced with text from another element
- Set up a computer with projector or large monitor. Does not include the description below: 'You can use a projector to show examples and demonstrate how to get started. '
- Warm-up Activity: Broadcast Game - the last sentence overflows the box and is partly hidden

### Hide and Seek
- Set up a computer with projector or large monitor. Does not include the description below: 'You can use a projector to show examples and demonstrate how to get started. '

**Comment by shrutidhariwal** [comment]
Thanks for noticing @chrisgarrity , have fixed the issues both in indesign and ppt files. This part _("Set up a computer with projector or large monitor. Does not include the description below: 'You can use a projector to show examples and demonstrate how to get started.")_ is not an error. We kept it that way as there was not enough space for the description, so we thought that it's ok to only highlight the main heading.

**Comment by shrutim15** [comment]
Thanks for noticing @chrisgarrity , have fixed the issues both in indesign and ppt files. This part _("Set up a computer with projector or large monitor. Does not include the description below: 'You can use a projector to show examples and demonstrate how to get started.")_ is not an error. We kept it that way as there was not enough space for the description, so we thought that it's ok to only highlight the main heading.
