### ISSUE TITLE
Update request: Scratch 3.0 Japanese versions of coding cards

### ISSUE THREAD

**Issue by Dobbsbigbear** [LLK/scratch-resources#76]
Current version of Scratch coding cards have any issues like "when green flag clicked". 
The cause is updating  translation of the blocks  for tablets  after I had gained screenshots for the cards.
I updated all PDFs of coding card to release corrected version. 
animation-cards.pdf, catch-cards.pdf, chase-cards.pdf, dance-cards.pdf, jumping-cards.pdf, music-cards.pdf, name-cards.pdf, pet-cards.pdf, pong-cards.pdf, story-cards.pdf, scratch-cards-all.pdf

also, I develop the new translated cards ,  video-cards.pdf

we  need to update the cards for Japanese elementary school  teachers as soon as possible.

**Comment by ntlrsk** [comment]
I think this is done - if not, please let us know.
